### ISSUE TITLE
Unknown config file format

### ISSUE THREAD

**Issue by DmitriyG228** [aiguofer/gspread-pandas#22]
Hi, 'Unknown config file format' error while parsing the google config file.

ConfigException                           Traceback (most recent call last)
<ipython-input-71-b216afc0a607> in <module>()
----> 1 Spread('y','w')

~/anaconda3/lib/python3.7/site-packages/gspread_pandas/client.py in __init__(self, user_creds_or_client, spread, sheet, config, create_spread, create_sheet, scope)
    282             self.client = user_creds_or_client
    283         elif isinstance(user_creds_or_client, (basestring, OAuth2Credentials)):
--> 284             self.client = Client(user_creds_or_client, config, scope)
    285         else:
    286             raise TypeError(

~/anaconda3/lib/python3.7/site-packages/gspread_pandas/client.py in __init__(self, user_or_creds, config, scope)
     72         #: `(list)` - Feeds included for the OAuth2 scope
     73         self.scope = scope
---> 74         self._login(user_or_creds, config)
     75 
     76     def _login(self, user_or_creds, config):

~/anaconda3/lib/python3.7/site-packages/gspread_pandas/client.py in _login(self, user_or_creds, config)
     78             creds = user_or_creds
     79         elif isinstance(user_or_creds, basestring):
---> 80             creds = get_creds(user_or_creds, config, self.scope)
     81         else:
     82             raise TypeError(

~/anaconda3/lib/python3.7/site-packages/gspread_pandas/conf.py in get_creds(user, config, scope)
    148         return run_flow(flow, storage, args)
    149 
--> 150     raise ConfigException("Unknown config file format")

ConfigException: Unknown config file format

**Comment by aiguofer** [comment]
Hey, sorry I was traveling when you created this and couldn't get to it.

Are you still experiencing this issue? If so, which type of google credentials are you using?

In the future, please wrap code and tracebacks in code blocks.

**Comment by gpetepg** [comment]
Hey,

Thanks for the reply. This was quite a while ago so I don't remeber off the
top of my head. Was definitely not the programmer I am today so I'm sure I
didn't format code correctly. I'll try to take a look when I can.

Best,
Tyler

**Comment by aiguofer** [comment]
Thanks anyway, since it's no longer an issue I will close this.
