### ISSUE TITLE
ConfigException from removing openid from scope

### ISSUE THREAD

**Issue by andmatt** [aiguofer/gspread-pandas#27]
This is related to the v2 branch.

So by [removing openid](https://github.com/aiguofer/gspread-pandas/commit/80214aba6997c85259664cacd7914274eeb63433) from the oauth scope, the following config exception occurs if you try to add a new user, BUT have an existing google secret saved in `.config`, from a project where `openid` is manually set as a scope. (I _think_ this was auto-configured for during setup?)

![image](https://user-images.githubusercontent.com/29054105/58499847-f20ed000-814e-11e9-87c9-3c2ce18c259e.png)

```
from gspread_pandas import Spread
s = Spread("gspread_test")

# prompts me to go to google oauth page and tells me to paste code in application

ConfigException: Scope has changed from "https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/userinfo.email" to "https://www.googleapis.com/auth/drive openid https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/userinfo.email".
```
I was able to fix this by either
1. adding openid back to `default_scopes`
2. creating a new project using the pypi instructions
3. deleting openid as a scope in the original project

Just wanted to call this out - might be helpful to add a message to change either the default scope or modify the project.

**Comment by aiguofer** [comment]
Ahh right, I knew there was a reason I had included `openid`... but when I tried removing it I didn't get the error anymore.

I wonder if the `oauth2client` oauth flow was adding `openid` by default? I'll need to look into that... I'd prefer not having any un-needed entries in the `default_scope`, but I also want it to be as painless of a transition as possible.
