### ISSUE TITLE
ServiceAccount does not work correctly

### ISSUE THREAD

**Issue by shredding** [aiguofer/gspread-pandas#29]
If you have a service account and you give access to it via the email. In this case, the file, when queried by drive looks like this:

```
{'id': 'some id here', 'name': 'some spreadheet name here'}]
```

This breaks here: https://github.com/aiguofer/gspread-pandas/blob/master/gspread_pandas/client.py#L256-L265

Since there is no parent, it raises an error, as it somehow expects said key to be there.

I hacked around that like this and it works:

```python
    def _list_spreadsheet_files(self, q):
        files = self._query_drive(q)

        for f in files:
            try:
                parent = next(
                    d for d in self._dirs + [self._root] if d["id"] in f.get("parents", {})
                )
                f["path"] = parent.get("path", "/")
            except StopIteration:
                f["path"] = "/"

        return remove_keys_from_list(files, ["parents"])
```

I'm not really, really sure what I'm doing here, hence I didn't make a PR. Happy to do so, if you think this would work.

**Comment by aiguofer** [comment]
Thanks for reporting! That's interesting that there's no parent in that scenario. I wonder where Google Drive is actually storing the file? I'm not 100% sure that defaulting to `f['path'] = "/"` in that scenario is the right thing to do, but otherwise the fix looks good to me and a PR would be great! I'm going to see if I can replicate on my end.

**Comment by aiguofer** [comment]
I was able to reproduce it locally. I'm surprised that the file shows up when querying drive since it doesn't seem like it's technically in the drive. I think in this case it might be better to leave the `path` blank since it's technically not in the root directory (otherwise the parent would be set to the ID of the root dir). The only place I thought this might cause a problem is in `move_file`, but taking a look in there I don't think it would cause any problems.

**Comment by shredding** [comment]
I made a PR with the code above, can change it to blank if you'd prefer ...

**Comment by shredding** [comment]
> I wonder where Google Drive is actually storing the file?

I'm not an expert, but I assume that this happens to files where you are not the owner?

**Comment by shredding** [comment]
Merged: https://github.com/aiguofer/gspread-pandas/pull/30

**Comment by aiguofer** [comment]
Interesting... so I found [this](https://developers.google.com/drive/api/v3/enable-shareddrives#behavioral_differences):

```
parents — A parent does not appear in the parents list if the requesting user is a not a member of the shared drive and does not have access to the parent. In addition, with the exception of the top level folder, the parents list must contain exactly one item if the file is located within a shared drive.
```

I created #31... but now I'm more sure the default when no parent is listed should not be "/". I'll play around with it to see if `None` or `""` is better (I think most things expect `path` to be a string).

**Comment by tfriedel** [comment]
I'm also having issues with this. The fix didn't fix it for me. I have no problem with the regular gspread.

**Comment by aiguofer** [comment]
@tfriedel hey, what error do you get with the fix in place?

I'm currently working on making the whole directory structure optional... it's convenient to have but it does make it a bit slower to instantiate.

**Comment by tfriedel** [comment]
It says insufficient permission. I think I only have rights to access the file, not to browse.

```
----> 2 sh2 = gspread_pandas.client.Spread(sheet_url, creds=credentials, scope=scope)

S:\toolkits\anaconda3-5.2.0\lib\site-packages\gspread_pandas\client.py in __init__(self, spread, sheet, config, create_spread, create_sheet, scope, user, creds, client, permissions)
    466             self.client = client
    467         else:
--> 468             self.client = Client(user, config, scope, creds)
    469 
    470         monkey_patch_request(self.client)

S:\toolkits\anaconda3-5.2.0\lib\site-packages\gspread_pandas\client.py in __init__(self, user, config, scope, creds, session)
    113         super().__init__(credentials, session)
    114 
--> 115         self._root = self._drive_request(file_id="root", params={"fields": "name,id"})
    116         self.refresh_directories()
    117 

S:\toolkits\anaconda3-5.2.0\lib\site-packages\gspread_pandas\client.py in _drive_request(self, method, file_id, params, data, headers)
    177         if file_id:
    178             url += "/{}".format(file_id)
--> 179         res = self.request(method, url, params=params, json=data)
    180         if res.text:
    181             return res.json()

S:\toolkits\anaconda3-5.2.0\lib\site-packages\gspread\client.py in request(self, method, endpoint, params, data, json, files, headers)
     77             return response
     78         else:
---> 79             raise APIError(response)
     80 
     81     def list_spreadsheet_files(self):

APIError: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission: Request had insufficient authentication scopes."
   }
  ],
  "code": 403,
  "message": "Insufficient Permission: Request had insufficient authentication scopes."
 }
}```

**Comment by aiguofer** [comment]
@tfriedel ahh that's due to the scope of your credentials.. you must not have `https://www.googleapis.com/auth/drive` in there. How did you obtain your credentials?

I hadn't really addressed the situation when people pass in their own scope or credentials without access to the `drive` API.... I'll add a fix for that today.

**Comment by tfriedel** [comment]
thanks, after I extended the scope it worked. I used
gspread_pandas.conf.get_config with a Service Account json.

Am Do., 11. Juli 2019 um 02:25 Uhr schrieb Diego Fernández Giraldo <
notifications@github.com>:

**Comment by aiguofer** [comment]
Ahh, you were using your own scope I take it? I've added some checks now so it'll still work and give you a message about the missing permissions (see https://github.com/aiguofer/gspread-pandas/commit/e8527fe56679088b333d66fa7c32c4a1e5b1db83).

Let me know if you have any other issues/suggestions/etc!

**Comment by aiguofer** [comment]
Btw, I just pushed a new version which should include all the aformentioned changes.
