### ISSUE TITLE
Look into shared Drives

### ISSUE THREAD

**Issue by aiguofer** [aiguofer/gspread-pandas#31]
There's some differences between files in a regular drive and those in shared drives [according to the API](https://developers.google.com/drive/api/v3/enable-shareddrives#behavioral_differences).

It seems like the current implementation might run into some problems with ^. I don't have shared drives so I haven't tested any of this, nor do I currently have time. I'm creating this issue to remember to look into it when possible, or if someone else can.

**Comment by aiguofer** [comment]
There's a few query parameters than can be passed to the API in order to enable querying across Shared Drives and allowing admin tasks if you're a shared drive admin. It's easy to add these, but then building the paths is less straightforward.

There's no way to enable getting all folders for all shared drives. Even if there was, it would probably take a while. One alternative would be to have a `drive_id` property for the client, so it uses that specific shared drive as root (and any file move operations would be with relation to the given drive).

**Comment by Joe-Heffer-Shef** [comment]
I need this feature

**Comment by aiguofer** [comment]
Hey @Joe-Heffer-Shef! I just noticed this ticket didn't get auto-closed by commit fb2942d. Shared drives were added recently by that commit.

The main changes added were:
- ability to open a sheet from a shared drive by name
- ability to move sheets by path to a shared drive

Is there anything else you're missing?

**Comment by Joe-Heffer-Shef** [comment]
Oh right, I didn't notice this feature in the documentation. I'm working on some code that iterates over directories and finds files  by searching by name in a shared drive using the Cloud API. These kinds of features might be out of scope for your project.

https://developers.google.com/drive/api/v3/search-files

**Comment by aiguofer** [comment]
So that's how we actually open files by name. You can take a look at `Client.list_spreadsheet_files`. There's also `Client.list_spreadsheet_files_in_folder` if you know the folder ID, and if you look at the `Client.directories` property, that fetches all directories that a user has access to (both in their own drive and in any shared drives). You can tell if it's a shared drive if the `path` doesn't start with a `/`.

**Comment by aiguofer** [comment]
That being said, everything here is focused on spreadsheets, so that won't list other file types. However, the code might be of use to you :)

Closing this issue, and let me know if there's any way I can help!
