### ISSUE TITLE
The service is currently unavailable error

### ISSUE THREAD

**Issue by citizen-seven** [aiguofer/gspread-pandas#32]
Gspread-pandas version 2.1.2 show error on trying to read the spreadsheet

```
APIError: {
  "error": {
    "code": 503,
    "message": "The service is currently unavailable.",
    "status": "UNAVAILABLE"
  }
}
```

**Comment by aiguofer** [comment]
Could you please include the whole stack trace to see what endpoint it's
hitting? It sounds like it's an issue with the Google API

**Comment by citizen-seven** [comment]
Google Sheet was to busy and returned 503 error.
