### ISSUE TITLE
Error adding permissions to the user

### ISSUE THREAD

**Issue by citizen-seven** [aiguofer/gspread-pandas#34]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/14357228/62527821-8dee4380-b844-11e9-9b39-3cc5955091b6.png">
fails on any argument to add_permissions method

**Comment by aiguofer** [comment]
Hey, sorry I've been traveling and hadn't had a chance to look. That function actually takes a list, not a string.

I guess I could add a `add_permission` function since adding a single permission is likely a common scenario. This would make it a bit more intuitive

**Comment by aiguofer** [comment]
Hopefully the above commit prevents this issue from happening in the future. Closing
