### ISSUE TITLE
Fix for RESOURCE_EXHAUSTED broken

### ISSUE THREAD

**Issue by rodelrod** [aiguofer/gspread-pandas#42]
Thanks for your work in this library, it's very handy. 

I'm using it for the first time and hitting the same `RESOURCE_EXHAUSTED` error mentioned in issue https://github.com/aiguofer/gspread-pandas/issues/25.

I believe this is due to a change in the error message sent by the Google API from "USER-100s" to ''Read requests per user per 100 seconds".

I've submitted a PR that fixes the issue for me and passes the tests: https://github.com/aiguofer/gspread-pandas/pull/41

```

**Comment by aiguofer** [comment]
Thanks for submitting this! I've gone ahead and merged it. I'm going to add a few other minor changes (mainly docs) and bump the patch version, hopefully by today.

**Comment by rodelrod** [comment]
Perfect, thanks!

**Comment by aiguofer** [comment]
This has been released in `2.2.1` now available in PyPi
