### ISSUE TITLE
Error in line 147 conf.py?

### ISSUE THREAD

**Issue by dh-metre** [aiguofer/gspread-pandas#44]
in conf.py line 147 : 

- `cfg_file = conf_dir / user` is returning an error which is preventing conf.get_creds() from completing.

- Error:  "gspread_pandas/conf.py", line 147, in get_creds, `creds_file = creds_dir / user`, gspread_pandas.exceptions.ConfigException: unsupported operand type(s) for /: 'str' and 'str'

I am trying to get the example code to run in repl.it and need to change the locations of the .config directories.  Here is the code I have inserted.

```
configuration = conf.get_config(conf_dir='gspread_pandas/', file_name='google_secret.json')
conf.get_creds(config=configuration, creds_dir='creds/')
```

**Comment by dh-metre** [comment]
to make it work creds_dir is type (Path) and not (str) as in documentation.

The following works now:

```
configuration = conf.get_config(conf_dir='config/', file_name='google_secret.json')
credentials = conf.get_creds(user='username@google.com', config=configuration, creds_dir=Path('config/'))
```

**Comment by aiguofer** [comment]
Hey! thanks for reporting. Glad you figured out a workaround. I've just fixed it, will push a patch today.
