### ISSUE TITLE
How to work with colab (finds only subset of all sheets)

### ISSUE THREAD

**Issue by samclark40** [aiguofer/gspread-pandas#50]
Hi, 
I'm trying to figure out how to pass the `creds` to `Spread`.

I'm in **Colab**, so it's a bit different than the standard user. 
To use `gspread` (not the pandas version) I authenticate like so:

``` python
from google.colab import auth
auth.authenticate_user()
import gspread
from oauth2client.client import GoogleCredentials
gc = gspread.authorize(GoogleCredentials.get_application_default())
```

But using `gspread_pandas.spread.Spread('sheetname',creds=?)` I'm lost as to what to supply here.

**Comment by samclark40** [comment]
Now saw the closed issues regarding colab.

This following works, so auth works now.
```python
import google.auth
from google.colab import auth
from gspread_pandas import Spread, Client

auth.authenticate_user()
credentials, project_id = google.auth.default()
myclient = gspread_pandas.client.Client(creds=credentials)
```

But there seems to be a scope issue.

```python
len(myclient.list_spreadsheet_files())
```
>108

But 
```python
from google.colab import auth
auth.authenticate_user()
import gspread
from oauth2client.client import GoogleCredentials
gc = gspread.authorize(GoogleCredentials.get_application_default())
```

```python
len(gc.list_spreadsheet_files())
```
>830

Therefore, I still cannot access my spreadsheet.
Any ideas what is going on?

**Comment by aiguofer** [comment]
Hi!

Thanks for reporting! Looking at the code, our query is a little different. The `gspread` params are:

```
        params = {
            'q': q,
            'pageSize': 1000,
            'supportsAllDrives': True,
            'includeItemsFromAllDrives': True,
        }
```
meanwhile the `gspread-pandas` params are:

```
{"q": q, "pageSize": 1000, "fields": "files(name,id,parents)"}
```

I'm guessing the difference you're seeing is due to shared drives.

`gspread-pandas` does a lot of handling files using paths, so I'll need to test that all of the path based stuff works with shared drives before I can enable it.
