### ISSUE TITLE
documentation vs implementation of Spread.__init__

### ISSUE THREAD

**Issue by mephinet** [aiguofer/gspread-pandas#52]
While trying to minimize API usage, I realized that the implementation and the documentation of `Spread.__init__` are inconsistent:

Whereas [the documentation](https://gspread-pandas.readthedocs.io/en/latest/gspread_pandas.html#gspread_pandas.spread.Spread) states that by default, no sheet is opened, the [actual implementation](https://github.com/aiguofer/gspread-pandas/blob/ab6cd02cd983b7676eec91a81da9cedeabbb4480/gspread_pandas/spread.py#L118) uses 0 as default value, which opens the first sheet.

While I would prefer the documented behavior, I guess, backwards-compatibility concerns will argue against me...

Thanks for creating gspread-pandas, Diego!

**Comment by aiguofer** [comment]
Hey! thanks for pointing this out, you're totally right, I'll fix the docs!

At this point I think indeed the backward-compatibility issue would make it hard to change the default... that being said if you explicitly pass `sheet=None` when instantiating a `Spread` object it would prevent it from opening the worksheet. That being said, there's no API calls made when calling `open_sheet`, so there's not a lot gained.

**Comment by mephinet** [comment]
Thanks for the quick merge, @aiguofer!
Regarding your comment "no API calls made": Hmm, when I enable the debug log level, I can see a number of API calls immediately happening when instantiating the `Spread`:
```
s = gsp.Spread("XY")
DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /drive/v3/files/root?fields=name%2Cid HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sheets.googleapis.com:443
DEBUG:urllib3.connectionpool:https://sheets.googleapis.com:443 "GET /v4/spreadsheets/XY?includeGridData=false HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://sheets.googleapis.com:443 "GET /v4/spreadsheets/XY?includeGridData=false HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://sheets.googleapis.com:443 "GET /v4/spreadsheets/XY?includeGridData=false HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://sheets.googleapis.com:443 "GET /v4/spreadsheets/XY?includeGridData=false HTTP/1.1" 200 None
```

This number decreases when specifying the sheet=None:
```
>>> s = gsp.Spread("XY", None)
DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /drive/v3/files/root?fields=name%2Cid HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sheets.googleapis.com:443
DEBUG:urllib3.connectionpool:https://sheets.googleapis.com:443 "GET /v4/spreadsheets/XY?includeGridData=false HTTP/1.1" 200 None
```
