### ISSUE TITLE
latest doc on readthedocs.io is empty

### ISSUE THREAD

**Issue by georgexsh** [aiguofer/gspread-pandas#53]
https://gspread-pandas.readthedocs.io/en/latest/gspread_pandas.html is empty.
but stable version works https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html.

**Comment by aiguofer** [comment]
Hey! thanks for reporting! I can't figure out what's wrong... if I build the docs locally it seems to be working just fine. I'm guessing it's some configuration setting in ReadTheDocs, but I've tried updating to python 3x for the build and installing the project, and it's still not working. I'll try to mess around with it whenever I get some more time.

**Comment by georgexsh** [comment]
It works now, thanks!
