### ISSUE TITLE
Gspread new versions split models module

### ISSUE THREAD

**Issue by floricar** [aiguofer/gspread-pandas#59]
Gspread new version 5.0.0 split models.py module and breaks the import of it. Reference [here](https://github.com/burnash/gspread/releases)

This issue should be fixed with this [PR](https://github.com/aiguofer/gspread-pandas/pull/58)

**Comment by aiguofer** [comment]
Thanks for raising this! Unfortunately, the requirements change alone will only affect future versions of this library and not really solve the underlying issue. I might accept the PR and do a patch release, but we'll still need to update the library to match v5 of gspread and do a major release.

**Comment by floricar** [comment]
yeap, I believe that is good way to tackle this
