### ISSUE TITLE
Gspread 5.0 compatibility

### ISSUE THREAD

**Issue by aiguofer** [aiguofer/gspread-pandas#60]
There have been various changes in the `gspread` library in the past year or so, including some breaking import changes in v5. We need to investigate what changes affect us and update `gspread-pandas` to match.

We'll need a major version release with the changes.

**Comment by mephinet** [comment]
I've seen you taged a new version, 2.3.1 yesterday, which works around this issue. Please don't forget to push it to pypi ;-) thanks!

**Comment by aiguofer** [comment]
@mephinet thanks for pointing that out! it seems like the Travis-ci automated deploy is broken so I manually pushed to PyPi

**Comment by astrochun** [comment]
I tried to install v2.3.1 but encountered some issues. `pip install gspread-pandas==2.3.1` failed to find it. I'm on python 3.8:
```
pip install --upgrade gspread-pandas==2.3.1
ERROR: Could not find a version that satisfies the requirement gspread-pandas==2.3.1 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.15.5, 0.15.6, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.1, 1.2.2, 1.3.0, 1.3.1, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0)
ERROR: No matching distribution found for gspread-pandas==2.3.1
```

**Comment by aiguofer** [comment]
@astrochun thanks for letting me know! turns out the new wheel didn't get pushed. I just fixed it and tested with python 3.8, should be working now!

**Comment by astrochun** [comment]
> @astrochun thanks for letting me know! turns out the new wheel didn't get pushed. I just fixed it and tested with python 3.8, should be working now!

Thanks for the quick response. I figured it was a wheel issue. I'll give it a try tomorrow. As an interim solution, I did the following in my requirements.txt:
````
gspread=4.0.1
gspread-pandas=2.3.0
```

**Comment by aiguofer** [comment]
nice, that should work as well!

**Comment by aiguofer** [comment]
v3 is now released and works with gspread >= 5 and also removes python 2 support, along with removing a couple dependencies.

**Comment by astrochun** [comment]
> v3 is now released and works with gspread >= 5 and also removes python 2 support, along with removing a couple dependencies.

This is great, I'll update and let you know if I encounter any unexpected issues. Thanks for your maintaining `gspread-pandas`
