### ISSUE TITLE
Error gspread_pandas.client.Spread

### ISSUE THREAD

**Issue by sgsen** [aiguofer/gspread-pandas#8]
line 91, in __init__
    self._config = config or get_config()

/conf.py", line 33, in get_config
    cfg = cfg[cfg.keys()[0]]

TypeError: 'dict_keys' object does not support indexing

Is python 3 not supported?

**Comment by aiguofer** [comment]
Sorry, it certainly should! I just still mainly work in 2.7 and had an oversight :(

I really need to create some tests... Anyway, fix is out now in version 0.15.1
