### ISSUE TITLE
Issue in frozen column count

### ISSUE THREAD

**Issue by tekendratimsina** [aiguofer/gspread-pandas#82]
Hello  Diego, 
I noticed one pretty minor issue while fetching frozen column count that resulted in error in sheet with frozen column for latest version.

`frozenColCount` should be replaced by `frozenColumnCount ` in https://github.com/aiguofer/gspread-pandas/blob/d04e57d4977712ccdd404bb34f1b7ae0468a1447/gspread_pandas/spread.py#L592 .

**Comment by tekendratimsina** [comment]
I create a pr for fix !

**Comment by aiguofer** [comment]
Thanks for your contribution! fix is released in 3.0.4
