### ISSUE TITLE
Google dropping support for OAuth out-of-band (oob) flow

### ISSUE THREAD

**Issue by koshy1123** [aiguofer/gspread-pandas#85]
I've been trying to get gspread-pandas to work with user credentials instead of the service account route, and noticed this hard-coded line which I think is impacting how I can use user credentials.

https://github.com/aiguofer/gspread-pandas/blob/5c37c6b6376f9188c349442825860f6ddf862c9a/gspread_pandas/conf.py#L156

According to google, this flow will not be supported anymore:
https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob

**Comment by aiguofer** [comment]
Thanks for reporting! Unfortunately this looks like it's going to require a bit of work which I'm not sure I have the bandwidth to do right now.

From reading the docs I think we'll need to start a webserver listening on localhost to capture the token on redirect. It could be done as a subprocess from within code, or the user could be asked to run a separate command to start the webserver only when they need to get the token. From a user perspective, you got any preferences?

**Comment by aiguofer** [comment]
nvm, found some docs with a much easier solution :) fix incoming. It's not a perfect solution for all situations (trying to run auth from a headless server won't work) but it's probably fine for most people.

**Comment by aiguofer** [comment]
fix released in 3.2.0
