### ISSUE TITLE
Documentation - Getting Started - bug in sample code

### ISSUE THREAD

**Issue by pytlv** [aiguofer/gspread-pandas#87]
Code from:
https://gspread-pandas.readthedocs.io/en/latest/getting_started.html
spread.update_cells('A1', 'A1', ['Created by:', spread.email])

Should be:
spread.update_cells('A1', 'B1', ['Created by:', spread.email])

**Comment by aiguofer** [comment]
thanks for pointing this out! will fix in next release :)

**Comment by aiguofer** [comment]
fixed in `3.2.1`
