### ISSUE TITLE
Instruction to generate OAuth is outdated

### ISSUE THREAD

**Issue by bmt800** [aiguofer/gspread-pandas#89]
At this line:
https://github.com/aiguofer/gspread-pandas/blob/master/README.rst?plain=1#L107

If we try to create an OAuth key right now at GCP, there is no option "Other" for application type.
Although It may be Web App or Desktop?

Thanks

**Comment by aiguofer** [comment]
Thanks for reporting! you're right, it's now Desktop App. I will update the README.
