### ISSUE TITLE
TypeError: data type "category" not understood

### ISSUE THREAD

**Issue by olly374** [aiguofer/gspread-pandas#9]
### Environment info
Raspberry Pi 1 Model B
Operating System: Raspbian Jessie (based on Debian 8)
Architecture: armhf
Python version: 3.4.2
gspread version: 0.15.1
pandas version: 0.14.1

### Steps undertaken
As per example on https://github.com/aiguofer/gspread-pandas#example
1) Set up and downloaded credentials as per guidance;
2) Replaced "http://www.ats.ucla.edu/stat/data/binary.csv" with "https://stats.idre.ucla.edu/stat/data/binary.csv" as file path has changed;
3) Replaced 'example_user', 'Example Spreadsheet', & sheet='New Test Sheet' with values specific to my project;
4) Run script: 
4a) Authenticated with link & provided activation code when prompted
4b) Error occurs

### Traceback
Traceback (most recent call last):
  File "gspreadPandas.py", line 21, in <module>
    spread.df_to_sheet(df, index=False, sheet='Sheet1', start='A2', replace=True)
  File "<string>", line 2, in df_to_sheet
  File "/usr/local/lib/python3.4/dist-packages/gspread_pandas/client.py", line 117, in _ensure_auth
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/gspread_pandas/client.py", line 576, in df_to_sheet
    df = fillna(df, fill_value)
  File "/usr/local/lib/python3.4/dist-packages/gspread_pandas/util.py", line 114, in fillna
    for col in df.dtypes[df.dtypes == 'category'].index:
  File "/usr/lib/python3/dist-packages/pandas/core/ops.py", line 572, in wrapper
    res = na_op(values, other)
  File "/usr/lib/python3/dist-packages/pandas/core/ops.py", line 535, in na_op
    result = lib.scalar_compare(x, y, op)
  File "lib.pyx", line 657, in pandas.lib.scalar_compare (pandas/lib.c:12114)
TypeError: data type "category" not understood

### Additional info 1
This script successfully works on the following environment:
Operating System: Windows 7 Pro x64
Architecture: AMD64
Python version: 3.4.0
gspread version: 0.15.1
pandas version: 0.20.3

I have attempted to install pandas 0.20.3 on the Raspberry Pi however whilst most required packages install succsessfully, python3-pandas-lib is not available form armhf therefore this updated version of pandas cannot be fully installed.

Upgrading to Stretch (Debian 9) may potentially fix this, however I am unable to do so due to current configuration limitations.

**Comment by aiguofer** [comment]
Hey, it looks like your Pandas version is too old. The error is coming from pandas because it doesn't understand the dtype "categorical". Looking at release notes, it looks like [this was done in 0.15](https://pandas.pydata.org/pandas-docs/stable/whatsnew.html#whatsnew-0150-cat)

I'll update the requirements to include a minimum Pandas version.

**Comment by olly374** [comment]
Thanks for getting back so quickly. Given that (AFAIK) Jessie currently only supports up to 14.1 (particulary given that it's an armhf architecture), do you know if any workarounds exist?

**Comment by aiguofer** [comment]
Hey! sorry I never got back to you. I actually have no experience with Jessie... is there no way to use pip to upgrade your Pandas version?

I could look into maybe adding some version check and only handle categoricals for versions where it's defined, although generally speaking, working with the latest Pandas version is ideal. Let me know if you've figured out a workaround and I can add something to the README.

**Comment by aiguofer** [comment]
Since I haven't heard back and you're using an un-supported version, I'm closing this.
