### ISSUE TITLE
RefreshError: 'invalid_client: Unauthorized'

### ISSUE THREAD

**Issue by yyzz1010** [aiguofer/gspread-pandas#96]
i've stored the credentials downloaded from google cloud console as "google_secret.json", `gspread_pandas.conf.get_config('./')` can read the file but with the below code there is error, however i could run this code last month... I tried to create a new credential but still not working :( please help thank you!

```python
spread = gspread_pandas.Spread('workbook name', config=gspread_pandas.conf.get_config('./'))
RefreshError: ('invalid_client: Unauthorized', {'error': 'invalid_client', 'error_description': 'Unauthorized'})

**Comment by aiguofer** [comment]
Hmm, there might be an issue with the previously saved creds file. Try deleting `~/.config/gspread_pandas/creds/default`.

**Comment by yyzz1010** [comment]
It works! Thank you~
